config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :movies
    resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, :overview, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @lists = List.all
    @movies = Movie.all
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create; end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists</h1>
</br>

<% @lists.each do |list| %>
  <h2><%= link_to list.name, list_path(list) %></h2>
<% end %>

</br>
<button type="button" class="btn btn-primary"><%= link_to 'Add New List', new_list_path %></button>

app/views/lists/new.html.erb
<%= simple_form_for @list do |create| %>
  <%= create.input :name %>
  <%= create.button :submit %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<% @movies.each do |movie| %>
<%= movie.title %>
<% end %>